final books = [
  {
    'id': 1,
    'title': 'Halloween',
    'author': 'Jim Kenneth',
    'year': '2005',
    'img': 'images/book1.jpg',
  },
  {
    'id': 2,
    'title': 'Old Town Road',
    'author': 'Terry Crews',
    'year': '1999',
    'img': 'images/book2.jpg',
  },
  {
    'id': 3,
    'title': 'Little Big City',
    'author': 'Tom Cruise',
    'year': '2011',
    'img': 'images/book3.jpg',
  },
  {
    'id': 4,
    'title': 'All Alone',
    'author': 'Janet Jay',
    'year': '2026',
    'img': 'images/book4.jpg',
  },
  {
    'id': 5,
    'title': 'Hotel',
    'author': 'Jay Cole',
    'year': '2001',
    'img': 'images/book5.jpg',
  },
  {
    'id': 6,
    'title': 'Miami',
    'author': 'Ryder Blue',
    'year': '2009',
    'img': 'images/book6.jpg',
  },
  {
    'id': 7,
    'title': 'Hostage',
    'author': 'Kenny Darshan',
    'year': '2029',
    'img': 'images/book7.jpg',
  },
  {
    'id': 8,
    'title': 'Colossal',
    'author': 'James Bond',
    'year': '2005',
    'img': 'images/book8.jpg',
  },
  {
    'id': 9,
    'title': 'Titan Bitch',
    'author': 'Godwin Brown',
    'year': '2011',
    'img': 'images/book9.jpg',
  },
];
